<main role="main" class="container">
	<form method="post" action="/editarTorcedor">
		<h3 class="mt-3">Editar torcedor</h3>
        <div class="row">
        	<div class="col-md-6">
        		<input type="hidden" name="id" value="<?=$this->view->dados['id']?>">
        		<div class="form-group">
		            <label for="nome">Nome</label>
		            <input class="form-control" type="text" id="nome" name="nome" placeholder="Digite seu Nome" value="<?=$this->view->dados['nome']?>" readonly>
		        </div>

		        <div class="form-group">
		            <label for="documento">Documento</label>
		            <input class="form-control" type="text" id="documento" name="documento" placeholder="Digite seu Documento" maxlength="15" value="<?=$this->view->dados['documento']?>" readonly>
		        </div>

		        <div class="form-group">
		            <label for="cep">CEP</label>
		            <input class="form-control" type="text" id="cep" name="cep" placeholder="Digite seu CEP" maxlength="8" value="<?=$this->view->dados['cep']?>" readonly>
		        </div>

		        <div class="form-group">
		            <label for="endereco">Endereço</label>
		            <input class="form-control" type="text" id="endereco" name="endereco" placeholder="Digite seu Endereço" value="<?=$this->view->dados['endereco']?>" readonly>
		        </div>

		        <div class="form-group">
		            <label for="bairro">Bairro</label>
		            <input class="form-control" type="text" id="bairro" name="bairro" placeholder="Digite seu Bairro" value="<?=$this->view->dados['bairro']?>" readonly>
		        </div>
        	</div>
        	<div class="col-md-6">
        		<div class="form-group">
		            <label for="cidade">Cidade</label>
		            <input class="form-control" type="text" id="cidade" name="cidade" placeholder="Digite sua cidade" value="<?=$this->view->dados['cidade']?>" readonly>
		        </div>

		        <div class="form-group">
		            <label for="uf">UF</label>
		            <input class="form-control" type="text" id="uf" name="uf" value="<?=$this->view->dados['uf']?>" readonly>
		        </div>

		        <div class="form-group">
		            <label for="telefone">Telefone</label>
		            <input class="form-control" type="text" id="telefone" name="telefone" placeholder="Digite seu telefone" maxlength="11" value="<?=$this->view->dados['telefone']?>">
		        </div>

		        <div class="form-group">
		            <label for="email">E-mail</label>
		            <input class="form-control" type="email" id="email" name="email" placeholder="Digite seu e-mail" value="<?=$this->view->dados['email']?>">
		        </div>

		        <label for="ativo">Ativo</label>
		        <div class="form-check">
		        	<input type="hidden" name="oculto" id="oculto" value="<?=$this->view->dados['ativo']?>">
				    <input class="form-check-input" type="radio" name="ativo" id="sim" value="1">
				    <label class="form-check-label" for="sim">
				    Sim
				   </label>
				</div>
				<div class="form-check">
				    <input class="form-check-input" type="radio" name="ativo" id="nao" value="0">
				    <label class="form-check-label" for="nao">
				    Não
				    </label>
				</div>
			</div>
        </div>
        <input class="btn btn-primary" type="submit" value="Salvar">

    </form>
    
</main>