
<div class="container">  
			<?php if($this->view->sucessoCadastro) { ?>

	            <small class="form-text text-success">E-mail enviado com sucesso!</small>

	        <?php } ?>
			<div class="py-3 text-center">
				<h2>Enviar e-mail</h2>
				<p class="lead">Enviar comunicado para o torcedor!</p>
			</div>

      		<div class="row">
      			<div class="col-md-12">
  				
					<div class="card-body font-weight-bold">
						<form action="/enviarEmail" method="post">
							<div class="form-group">
								<label for="email">E-mail</label>
								<input name="email" type="email" class="form-control" id="email" value="<?= $this->view->email ?>">
							</div>

							<div class="form-group">
								<label for="assunto">Assunto</label>
								<input name="assunto" type="text" class="form-control" id="assunto" placeholder="Assundo do e-mail">
							</div>

							<div class="form-group">
								<label for="mensagem">Mensagem</label>
								<textarea name="mensagem" class="form-control" id="mensagem"></textarea>
							</div>

							<button type="submit" class="btn btn-primary btn-lg">Enviar Mensagem</button>
						</form>
					</div>
				</div>
      		</div>
      	</div>

      	<?php
      		print_r($this->view->email);
      	?>