<main role="main" class="container">
	<form method="post" action="/novoTorcedor">
		<h3 class="mt-3">Novo torcedor</h3>

		<?php if($this->view->sucessoCadastro) { ?>

            <small class="form-text text-success">Dados inserido com sucesso!</small>

        <?php } ?>
        <?php if($this->view->erroCadastro) { ?>

            <small class="form-text text-danger">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente.</small>

        <?php } ?>

        <div class="row">
        	<div class="col-md-6">
        		<div class="form-group">
		            <label for="nome">Nome</label>
		            <input class="form-control" type="text" id="nome" name="nome" placeholder="Digite seu Nome">
		        </div>

		        <div class="form-group">
		            <label for="documento">Documento</label>
		            <input class="form-control" type="text" id="documento" name="documento" placeholder="Digite seu Documento" maxlength="15">
		        </div>

		        <div class="form-group">
		            <label for="cep">CEP</label>
		            <input class="form-control" type="text" id="cep" name="cep" placeholder="Digite seu CEP" maxlength="8">
		        </div>

		        <div class="form-group">
		            <label for="endereco">Endereço</label>
		            <input class="form-control" type="text" id="endereco" name="endereco" placeholder="Digite seu Endereço">
		        </div>

		        <div class="form-group">
		            <label for="bairro">Bairro</label>
		            <input class="form-control" type="text" id="bairro" name="bairro" placeholder="Digite seu Bairro">
		        </div>
        	</div>
        	<div class="col-md-6">
        		<div class="form-group">
		            <label for="cidade">Cidade</label>
		            <input class="form-control" type="text" id="cidade" name="cidade" placeholder="Digite sua cidade">
		        </div>

		        <div class="form-group">
		            <label for="uf">UF</label>
		            <select class="form-control" id="uf" name="uf">
		                <option value="">Selecione</option>
		                <option value="AC">Acre</option>
					    <option value="AL">Alagoas</option>
					    <option value="AP">Amapá</option>
					    <option value="AM">Amazonas</option>
					    <option value="BA">Bahia</option>
					    <option value="CE">Ceará</option>
					    <option value="DF">Distrito Federal</option>
					    <option value="ES">Espírito Santo</option>
					    <option value="GO">Goiás</option>
					    <option value="MA">Maranhão</option>
					    <option value="MT">Mato Grosso</option>
					    <option value="MS">Mato Grosso do Sul</option>
					    <option value="MG">Minas Gerais</option>
					    <option value="PA">Pará</option>
					    <option value="PB">Paraíba</option>
					    <option value="PR">Paraná</option>
					    <option value="PE">Pernambuco</option>
					    <option value="PI">Piauí</option>
					    <option value="RJ">Rio de Janeiro</option>
					    <option value="RN">Rio Grande do Norte</option>
					    <option value="RS">Rio Grande do Sul</option>
					    <option value="RO">Rondônia</option>
					    <option value="RR">Roraima</option>
					    <option value="SC">Santa Catarina</option>
					    <option value="SP">São Paulo</option>
					    <option value="SE">Sergipe</option>
					    <option value="TO">Tocantins</option>
		            </select>
		        </div>

		        <div class="form-group">
		            <label for="telefone">Telefone</label>
		            <input class="form-control" type="text" id="telefone" name="telefone" placeholder="Digite seu telefone" maxlength="11">
		        </div>

		        <div class="form-group">
		            <label for="email">E-mail</label>
		            <input class="form-control" type="email" id="email" name="email" placeholder="Digite seu e-mail">
		        </div>

		        <label for="email">Ativo</label>
		        <div class="form-check">
				    <input class="form-check-input" type="radio" name="ativo" id="sim" value="sim">
				    <label class="form-check-label" for="sim">
				    Sim
				   </label>
				</div>
				<div class="form-check">
				    <input class="form-check-input" type="radio" name="ativo" id="nao" value="nao">
				    <label class="form-check-label" for="nao">
				    Não
				    </label>
				</div>
			</div>
        </div>
        <input class="btn btn-primary" type="submit" value="Salvar">

    </form>
    
</main>