<main role="main" class="container">
	<?php if($this->view->sucessoCadastro) { ?>

        <small class="form-text text-success">Dados inseridos com sucesso!</small>

    <?php } ?>
	<div class="enviar">
		<h3 class="mt-4">Enviar arquivo XML</h3>
		<form enctype="multipart/form-data" action="/enviado" method="post">
			<div class="form-group">
		        <label for="arquivo">Arquivo XML</label>
		        <input class="form-control-file" type="file" name="arquivo" id="arquivo">
		    </div>
		    <div class="form-group">
		        <button type="submit" class="btn btn-success">Enviar</button>
		    </div>
		</form>
	</div>
</main>
