<html>
<head>
    <meta charset="utf-8" />
    <title>All Blacks</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/dataTables.bootstrap4.min.css">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script src="/js/jquery-3.3.1.js"></script>
    <script src="/js/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
    <script src="/js/jquery.dataTables.min.js"></script>
    <script src="/js/dataTables.bootstrap4.min.js"></script>
    <script src="/js/popper.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/script.js"></script>

    <link rel="stylesheet" type="text/css" href="/css/style.css">

</head>

<body>
<!--Top-Menu-->
<header>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">

        <!-- Logo -->
        <a href="/" class="navbar-brand">All Blacks</a>

        <!-- Menu Hamburguer -->
        <button class="navbar-toggler" data-toggle="collapse"
                data-target="#navegacao">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- navegacao -->
        <div class="collapse navbar-collapse" id="navegacao">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="/" class="nav-link">Principal</a>
                </li>
                <li class="nav-item">
                    <a href="/enviar" class="nav-link">Enviar torcedores</a>
                </li>
                <li class="nav-item">
                    <a href="/torcedores" class="nav-link">Torcedores</a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<!--Top-Menu-->

{% block content %}
{% endblock %}

<!-- Footer -->
<footer>
    <div class="footer-copyright text-center white py-3">© 2018 Copyright:
        <a href="#"> Thales Assis</a>
    </div>
</footer>
<!-- Footer -->
<script>
    $(document).ready(function() {
        $('#example').DataTable({
            "oLanguage": {
                "sProcessing": "Aguarde enquanto os dados são carregados ...",
                "sLengthMenu": "Mostrar _MENU_ registros por pagina",
                "sZeroRecords": "Nenhum registro correspondente ao criterio encontrado",
                "sInfoEmtpy": "Exibindo 0 a 0 de 0 registros",
                "sInfo": "Exibindo de _START_ a _END_ de _TOTAL_ registros",
                "sInfoFiltered": "",
                "sSearch": "Procurar",
                "oPaginate": {
                    "sFirst":    "Primeiro",
                    "sPrevious": "Anterior",
                    "sNext":     "Próximo",
                    "sLast":     "Último"
                }
            }
        });
    });
</script>
</body>
</html>
